id: Handle Hello World Premium Alert
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: Handle Hello World Premium Alert
description: This is a playbook which will handle the alerts coming from the Hello
  World Premium service
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a3fa6343-393c-4446-88ec-cf5678c98979
    type: start
    task:
      id: a3fa6343-393c-4446-88ec-cf5678c98979
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 1b6ff550-bde1-431d-88d9-3f2b62b15bdb
    type: regular
    task:
      id: 1b6ff550-bde1-431d-88d9-3f2b62b15bdb
      version: -1
      name: Get alert details
      description: Retrieve alert details for a HelloWorldPremium alert by alert ID
      script: '|||helloworldpremium-get-alert'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      alert_id:
        simple: ${inputs.AlertID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 240,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: AlertID
  value:
    simple: ${incident.helloworldpremiumid}
  required: false
  description: Alert ID to retrieve details for. By default retrieves from the HelloWorldPremium
    ID custom field in the HelloWorldPremium incident type
  playbookInputQuery: null
outputs: []
